server:
  port: ${DISPATCHER_PORT:8084}

telegram:
  bot:
    token: ${TELEGRAM_BOT_TOKEN}
    uri: ${TELEGRAM_BOT_URL}

spring:
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USERNAME}
    password: ${RABBIT_PASSWORD}
    queues:
      text-message-update: rabbit.text.message.update.queue
      doc-message-update: rabbit.doc.message.update.queue
      photo-message-update: rabbit.photo.message.update.queue
      answer-message: rabbit.answer.message.queue

logging:
  level:
    root: INFO
    com.github.provitaliy: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
