server:
  port: 8081

telegram:
  bot:
    token: ${TELEGRAM_BOT_TOKEN}

spring:
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "admin"
    password: "0238"
    queues:
      text-message-update: rabbit.text.message.update.queue
      doc-message-update: rabbit.doc.message.update.queue
      photo-message-update: rabbit.photo.message.update.queue
      answer-message: rabbit.answer.message.queue

logging:
  level:
    root: INFO
    com.github.provitaliy: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
