server:
  port: ${MAIL_SERVICE_PORT:8087}

spring:
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    protocol: ${MAIL_PROTOCOL:smtps}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USERNAME}
    password: ${RABBIT_PASSWORD}
    queues:
      registration-mail: "rabbit.registration.mail.queue"

service:
  activation:
    uri: ${USER_ACTIVATION_URL}