server:
  port: 8087

spring:
  mail:
    host: smtp.yandex.ru
    port: ${MAIL_PORT:465}
    protocol: ${MAIL_PROTOCOL:smtps}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: "0238"
    queues:
      registration-mail: "rabbit.registration.mail.queue"

service:
  activation:
    uri: "http://127.0.0.1:8086/user/activateUser?id={id}"