server:
  port: 8082

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: "0238"
    queues:
  datasource:
    url: "jdbc:postgresql://localhost:5432/tgsharedb"
    username: admin
    password: "0238"
  jpa:
    hibernate:
      ddl-auto: create-drop

telegram:
  bot:
    token: ${TELEGRAM_BOT_TOKEN}
  endpoints:
    file-info: "https://api.telegram.org/bot{token}/getFile?file_id={fileId}"
    file-storage: "https://api.telegram.org/file/bot{token}/{filePath}"

files:
  link: "${REST_SERVICE_URI:http://localhost:8086}"

logging:
  level:
    root: INFO
    com.github.provitaliy: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

salt: ${SALT:test}