server:
  port: ${NODE_PORT:8085}

spring:
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USERNAME}
    password: ${RABBIT_PASSWORD}
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create-drop

telegram:
  bot:
    token: ${TELEGRAM_BOT_TOKEN}
  endpoints:
    file-info: ${TG_BOT_FILE_INFO_URL}
    file-storage: ${TG_BOT_FILE_STORAGE_URL}

files:
  link: "${REST_SERVICE_URL:http://localhost:8086}"

logging:
  level:
    root: INFO
    com.github.provitaliy: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

salt: ${SALT:test}