server:
  port: ${REST_SERVICE_PORT:8086}

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create-drop

salt: ${SALT:test}